# The following patch adds an approval annotation to HVPA
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.kubernetes.io: "unapproved, temporarily squatting" # see https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2337-k8s.io-group-protection
  name: hvpas.autoscaling.k8s.io
